module.exports = {
   ADD_TO_CART: 'ADD_TO_CART', 
   EMPTY_CART: 'EMPTY_CART', 
   UPDATE_CART: 'UPDATE_CART',
   SEARCH_DATA: 'SEARCH_DATA',
   REMOVE_ITEM: 'REMOVE_ITEM',
   PURCHAE_MADE: 'PURCHAE_MADE',
   EDIT_ITEM: "EDIT_ITEM",
   DELETE_ITEM: 'DELETE_ITEM'
}